spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: ${ACCOUNT_NAME}
          account-key: ${ACCOUNT_KEY}
          endpoint: ${ENDPOINT}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


file:
  upload-dir: ./uploads